export const AUTH = {
  REGISTER: 'AUTH_REGISTER' as const,
  LOGIN: 'AUTH_LOGIN' as const,
  LOGOUT: 'AUTH_LOGOUT' as const,
  AUTO_LOGIN: 'AUTH_AUTO_LOGIN' as const,
};

export const USER = {
  GET_USER: 'USER_GET_USER' as const,
  GET_USER_SUCCESS: 'USER_GET_USER_SUCCESS' as const,
  ERROR: 'USER_ERROR' as const,
};

export const PROFILE = {
  GET_USER_INFO: 'PROFILE_GET_USER_INFO' as const,
  GET_USER_INFO_SUCCESS: 'PROFILE_GET_USER_INFO_SUCCESS' as const,
  UPDATE_USER_INFO: 'PROFILE_UPDATE_USER_INFO' as const,
  UPDATE_USER_INFO_SUCCESS: 'PROFILE_UPDATE_USER_INFO_SUCCESS' as const,
  ERROR: 'PROFILE_ERROR' as const,
};

export const FRIENDSHIP = {
  GET_ALL_FRIENDSHIPS: 'FRIENDSHIP_GET_ALL_FRIENDSHIPS' as const,
  GET_ALL_FRIENDSHIPS_SUCCESS: 'FRIENDSHIP_GET_ALL_FRIENDSHIPS_SUCCESS' as const,
  GET_FRIENDSHIP: 'FRIENDSHIP_GET_FRIENDSHIP' as const,
  GET_FRIENDSHIP_SUCCESS: 'FRIENDSHIP_GET_FRIENDSHIP_SUCCESS' as const,
  CREATE_FRIENDSHIP: 'FRIENDSHIP_CREATE_FRIENDSHIP' as const,
  CREATE_FRIENDSHIP_SUCCESS: 'FRIENDSHIP_CREATE_FRIENDSHIP_SUCCESS' as const,
  ACCEPT_FRIENDSHIP: 'FRIENDSHIP_ACCEPT_FRIENDSHIP' as const,
  ACCEPT_FRIENDSHIP_SUCCESS: 'FRIENDSHIP_ACCEPT_FRIENDSHIP_SUCCESS' as const,
  DELETE_FRIENDSHIP: 'FRIENDSHIP_DELETE_FRIENDSHIP' as const,
  DELETE_FRIENDSHIP_SUCCESS: 'FRIENDSHIP_DELETE_FRIENDSHIP_SUCCESS' as const,
  ERROR: 'FRIENDSHIP_ERROR' as const,
};

export const POST = {
  CREATE_POST: 'POST_CREATE_POST' as const,
  CREATE_POST_SUCCESS: 'POST_CREATE_POST_SUCCESS' as const,
  GET_FEED: 'POST_GET_FEED' as const,
  GET_FEED_SUCCESS: 'POST_GET_FEED_SUCCESS' as const,
  GET_SELECTED_POST: 'POST_GET_SELECTED_POST' as const,
  GET_SELECTED_POST_SUCCESS: 'POST_GET_SELECTED_POST_SUCCESS' as const,
  UPDATE_POST: 'POST_UPDATE_POST' as const,
  UPDATE_POST_SUCCESS: 'POST_UPDATE_POST_SUCCESS' as const,
  DELETE_POST: 'POST_DELETE_POST' as const,
  DELETE_POST_SUCCESS: 'POST_DELETE_POST_SUCCESS' as const,
  ADD_POST_REACTION: 'POST_ADD_POST_REACTION' as const,
  DELETE_POST_REACTION: 'POST_DELETE_POST_REACTION' as const,
  DELETE_POST_REACTION_SUCCESS: 'POST_DELETE_POST_REACTION_SUCCESS' as const,
  ERROR: 'POST_ERROR' as const,
};

export const COMMENT = {
  CREATE_COMMENT: 'COMMENT_CREATE_COMMENT',
  CREATE_COMMENT_SUCCESS: 'COMMENT_CREATE_COMMENT_SUCCESS',
  DELETE_COMMENT: 'COMMENT_DELETE_COMMENT',
  DELETE_COMMENT_SUCCESS: 'COMMENT_DELETE_COMMENT_SUCCESS',
  ADD_COMMENT_REACTION: 'COMMENT_ADD_COMMENT_REACTION',
  ADD_COMMENT_REACTION_SUCCESS: 'COMMENT_ADD_COMMENT_REACTION_SUCCESS',
  DELETE_COMMENT_REACTION: 'COMMENT_DELETE_COMMENT_REACTION',
  DELETE_COMMENT_REACTION_SUCCESS: 'COMMENT_DELETE_COMMENT_REACTION_SUCCESS',
};

export const CHAT = {
  GET_CHATS: 'CHAT_GET_CHATS' as const,
  GET_CHATS_SUCCESS: 'CHAT_GET_CHATS_SUCCESS' as const,
  GET_SELECTED_CHAT: 'CHAT_GET_CHAT' as const,
  GET_SELECTED_CHAT_SUCCESS: 'CHAT_GET_CHAT_SUCCESS' as const,
  ERROR: 'CHAT_ERROR' as const,
};

export const MESSAGE = {
  CREATE_MESSAGE: 'MESSAGE_CREATE_MESSAGE' as const,
  ADD_MESSAGE: 'MESSAGE_ADD_MESSAGE' as const,
  ADD_MESSAGE_SUCCESS: 'MESSAGE_ADD_MESSAGE_SUCCESS' as const,
  ADD_MESSAGE_REACTION: 'MESSAGE_ADD_MESSAGE_REACTION' as const,
  UPDATE_MESSAGE: 'MESSAGE_UPDATE_MESSAGE' as const,
  DELETE_MESSAGE_REACTION: 'MESSAGE_DELETE_MESSAGE_REACTION' as const,
  DELETE_MESSAGE_REACTION_SUCCESS: 'MESSAGE_DELETE_MESSAGE_REACTION_SUCCESS' as const,
};

export const NOTIFICATION = {
  GET_MY_NOTIFICATIONS: 'NOTIFICATION_GET_MY_NOTIFICATIONS' as const,
  GET_MY_NOTIFICATIONS_SUCCESS: 'NOTIFICATION_GET_MY_NOTIFICATIONS_SUCCESS' as const,
  GET_NOT_SEEN_NOTIFICATIONS_COUNT: 'NOTIFICATION_GET_NOT_SEEN_NOTIFICATIONS_COUNT' as const,
  GET_NOT_SEEN_NOTIFICATIONS_COUNT_SUCCESS: 'NOTIFICATION_GET_NOT_SEEN_NOTIFICATIONS_COUNT_SUCCESS' as const,
  ADD_NOTIFICATION: 'NOTIFICATION_ADD_NOTIFICATION' as const,
  ADD_NOTIFICATION_SUCCESS: 'NOTIFICATION_ADD_NOTIFICATION_SUCCESS' as const,
  HIDE_NEW_NOTIFICATION: 'NOTIFICATION_HIDE_NEW_NOTIFICATION' as const,
  RESET_NOTIFICATIONS: 'NOTIFICATION_RESET_NOTIFICATIONS' as const,
  MARK_AS_SEEN_BY_ID: 'NOTIFICATION_MARK_AS_SEEN_BY_ID' as const,
  MARK_AS_SEEN_BY_ID_SUCCESS: 'NOTIFICATION_MARK_AS_SEEN_BY_ID_SUCCESS' as const,
  ERROR: 'NOTIFICATION_ERROR' as const,
};
